# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

swift_version = "3.0"
use_frameworks!

target 'NewsFeed' do
  pod 'JGProgressHUD'
  pod 'SDWebImage', '~>3.8'
  pod 'Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Alamofire'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
